---
title: "Overview"
author: "Minling Xiao"
date: "2023"
output: md_document
---

This application aims to visualize access to alcohol outlets in Auckland, New Zealand including:

+ visualizing the geographic locations of existing on-license and off-license alcohol outlets (**Map on the right**);
+ visualizing the density of existing on on-license and off-license alcohol outlets respectively (**Density tabs**);
+ visualizing the change of the existing off-license alcohol outlets density while different rules are applied (**School & Marae tab**):
    * restriction on off-license alcohol outlets within some distance from schools;
    * restriction on off-license alcohol outlets within some distance from marae;
    * restriction on distance between off-license alcohol outlets.
    
To accommodate the varying policies on alcohol sales in different parts of Auckland, the landmass of the city is divided into four distinct areas for visualization purposes in the Shiny App: Trust – Waitakere, Trust – Portage, CBD, and the rest of Auckland. Researchers and policymakers may better comprehend and analyze the effects of various alcohol outlet rules on these regions. This divide enables a more targeted analysis of alcohol-related problems and the effectiveness of different policies within each specific area. The Auckland city is divided into:

+ **Trust – Waitakere**: This area refers to the region of Auckland governed by the Waitakere Licensing Trust which has its own policies and regulations regarding the establishment and operation of alcohol outlets within its jurisdiction.
    
+	**Trust – Portage**: Similar to the Waitakere Trust, this area represents the portion of Auckland that falls under the jurisdiction of the Portage Licensing Trust. This trust implements its own set of policies and guidelines related to alcohol sales and distribution.

+ **The Central Business District - CBD**: The CBD area represents the core commercial and urban center of Auckland.

+ **The rest of Auckland**: The remaining area of Auckland encompasses the regions that are not in CBD and are not specifically governed by either the Waitakere Licensing Trust or the Portage Licensing Trust.
	  
The map on the right shows the current situation of both on-license and off-license alcohol outlets. Clicking the layer icon on top left of the map allows you to display the distribution of on-license and off-license outlets in Auckland.

    
    